version: "3"
services:
  dask-scheduler:
    build:
      context: .
      dockerfile: release/Dockerfile.tiny
    image: rousik/pudl
    ports:
      - "8786:8786"
      - "8787:8787"
    command: ["dask-scheduler"]

  dask-worker-1:
    image: rousik/pudl
    depends_on:
      - dask-scheduler
    command: ["dask-worker", "tcp://dask-scheduler:8786"]
    volumes:
      # - ${GCP_KEY_PATH}:/tmp/keys/gcp-keyfile.json:ro
      - datapkg:/pudl/outputs/datapkg
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/keys/gcp-keyfile.json
  dask-worker-2:
   image: rousik/pudl
   depends_on:
     - dask-scheduler
   command: ["dask-worker", "tcp://dask-scheduler:8786"]
   volumes:
      # - ${GCP_KEY_PATH}:/tmp/keys/gcp-keyfile.json:ro
      - datapkg:/pudl/outputs/datapkg
   environment:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/keys/gcp-keyfile.json
  etl:
    env_file:
      - docker.env
    image: rousik/pudl
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/keys/gcp-keyfile.json
    depends_on:
      - dask-scheduler
      - dask-worker-1
      - dask-worker-2
    command: [
      "pudl_etl",
      "-c",
      "--dask-executor-address=tcp://dask-scheduler:8786",
      # "--show-flow-graph",
      # "--rerun=2021-01-29-0546-616a38e4-8bbb-4cfd-8f01-47ff72ec3d68",
      # "/pudl/src/release/settings/release.yml",
      "/pudl/src/release/settings/test.yml",
      ]
    # volumes:
      # - ${GCP_KEY_PATH}:/tmp/keys/gcp-keyfile.json:ro
        # - datapkg:/pudl/outputs/datapkg
volumes:
  datapkg:
